//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileManageSysyem.EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileInfo
    {
        public int Mid { get; set; }
        public string Brand { get; set; }
        public string Type { get; set; }
        public Nullable<int> Price { get; set; }
        public int Cid { get; set; }
    
        public virtual CategoryInfo CategoryInfo { get; set; }
    }
}
